# Custom Language File for Launcher Customizer

[ejs.app]
title = "Warcrime Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/WarcrimeLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#" 
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/adv93E2HCC"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/WarcrimeLauncher"
supportLink = "https://github.com/dscalZi/WarcrimeLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO RE: WARCRIMES"
welcomeDescription = "The Warcrimes server hosting a custom modpack for Minecraft 1.16.5 with friends."
welcomeDescCTA = "You are just a few clicks away from Magic, Chaos and Timetravel!"
